apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: registry.cn-hangzhou.aliyuncs.com/testyxm/nodejs.demo
        ports:
        - containerPort: 80
